"""MVP validator contracts — all 15 validators from the validation matrix."""

from __future__ import annotations

from film_pipeline.schemas._base import ValidationModality, ValidationScope
from film_pipeline.schemas.registries.validator_registry import (
    ValidatorRegistryEntry,
    ValidatorThresholds,
)

MVP_VALIDATORS: list[ValidatorRegistryEntry] = [
    # --- Text validators (artifact scope) ---
    ValidatorRegistryEntry(
        validator_id="logline-validator",
        scope=ValidationScope.ARTIFACT,
        modalities=[ValidationModality.TEXT],
        input_schema="logline",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["unclear_premise", "missing_emotional_hook"],
        warning_conditions=["too_long", "generic_language"],
    ),
    ValidatorRegistryEntry(
        validator_id="treatment-validator",
        scope=ValidationScope.ARTIFACT,
        modalities=[ValidationModality.TEXT],
        input_schema="treatment",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["missing_acts", "no_theme"],
        warning_conditions=["overlong", "weak_act_breaks"],
    ),
    ValidatorRegistryEntry(
        validator_id="scene-writing-validator",
        scope=ValidationScope.SCENE,
        modalities=[ValidationModality.TEXT],
        input_schema="scene_script",
        models=["gemini-flash", "gpt-5-mini"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["missing_scene_intent", "no_conflict"],
        warning_conditions=["dialogue_dense", "scene_too_long"],
    ),
    ValidatorRegistryEntry(
        validator_id="dialogue-voice-validator",
        scope=ValidationScope.SCENE,
        modalities=[ValidationModality.TEXT],
        input_schema="scene_script",
        models=["gpt-5-mini"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["voice_inconsistency", "character_truth_broken"],
        warning_conditions=["generic_dialogue", "exposition_heavy"],
    ),
    ValidatorRegistryEntry(
        validator_id="character-dossier-validator",
        scope=ValidationScope.ARTIFACT,
        modalities=[ValidationModality.TEXT, ValidationModality.IMAGE],
        input_schema="character_bible",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=80, review_at=70, block_below=70),
        blocking_conditions=["missing_visual_identity", "no_must_not_change"],
        warning_conditions=["generic_appearance", "incomplete_wardrobe"],
    ),
    ValidatorRegistryEntry(
        validator_id="environment-bible-validator",
        scope=ValidationScope.ARTIFACT,
        modalities=[ValidationModality.TEXT, ValidationModality.IMAGE],
        input_schema="environment_bible",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=80, review_at=70, block_below=70),
        blocking_conditions=["missing_locked_prompt_block", "no_lighting_profiles"],
        warning_conditions=["inconsistent_time_of_day", "missing_props"],
    ),
    ValidatorRegistryEntry(
        validator_id="reference-usability-validator",
        scope=ValidationScope.ARTIFACT,
        modalities=[ValidationModality.IMAGE],
        input_schema="reference_strategy",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["low_resolution", "moderation_risk", "wrong_subject"],
        warning_conditions=["poor_lighting", "non_matching_style"],
    ),
    # --- Camera + design validators ---
    ValidatorRegistryEntry(
        validator_id="shot-design-validator",
        scope=ValidationScope.ARTIFACT,
        modalities=[ValidationModality.TEXT, ValidationModality.CAMERA],
        input_schema="master_film_matrix",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["missing_coverage", "no_camera_profile"],
        warning_conditions=["repetitive_framing", "missing_transitions"],
    ),
    ValidatorRegistryEntry(
        validator_id="prompt-readiness-validator",
        scope=ValidationScope.ARTIFACT,
        modalities=[ValidationModality.TEXT],
        input_schema="prompt_package",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["malformed_rctco", "missing_refs", "prompt_too_long"],
        warning_conditions=["ambiguous_constraints", "missing_examples"],
    ),
    # --- Video validators (clip scope) ---
    ValidatorRegistryEntry(
        validator_id="clip-quality-validator",
        scope=ValidationScope.CLIP,
        modalities=[ValidationModality.VIDEO],
        input_schema="generated_clip",
        models=["gemini-flash", "gpt-5-mini"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["corrupt_asset", "wrong_duration", "black_frame"],
        warning_conditions=["compression_artifacts", "motion_blur", "lighting_issue"],
    ),
    ValidatorRegistryEntry(
        validator_id="prompt-adherence-validator",
        scope=ValidationScope.CLIP,
        modalities=[ValidationModality.VIDEO],
        input_schema="generated_clip",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["wrong_character", "wrong_environment", "missing_action"],
        warning_conditions=["partial_adherence", "extra_elements"],
    ),
    # --- Continuity + flow validators ---
    ValidatorRegistryEntry(
        validator_id="scene-continuity-validator",
        scope=ValidationScope.SCENE,
        modalities=[ValidationModality.CONTINUITY],
        input_schema="scene_clips",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["character_state_mismatch", "prop_disappeared"],
        warning_conditions=["lighting_shift", "wardrobe_minor_drift"],
    ),
    ValidatorRegistryEntry(
        validator_id="act-structure-validator",
        scope=ValidationScope.ACT,
        modalities=[ValidationModality.TEXT, ValidationModality.FLOW],
        input_schema="act_clips",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=80, review_at=70, block_below=70),
        blocking_conditions=["broken_narrative_arc", "missing_climax"],
        warning_conditions=["pacing_issue", "weak_transitions"],
    ),
    ValidatorRegistryEntry(
        validator_id="full-movie-flow-validator",
        scope=ValidationScope.FULL_MOVIE,
        modalities=[ValidationModality.FLOW, ValidationModality.CONTINUITY],
        input_schema="full_movie",
        models=["gemini-flash", "gpt-5-mini"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["emotional_arc_broken", "major_continuity_gap"],
        warning_conditions=["pacing_drift", "minor_continuity_note"],
    ),
    # --- Assembly validator ---
    ValidatorRegistryEntry(
        validator_id="assembly-validator",
        scope=ValidationScope.DELIVERY,
        modalities=[ValidationModality.ASSEMBLY],
        input_schema="assembly_manifest",
        models=["gemini-flash"],
        thresholds=ValidatorThresholds(pass_at=85, review_at=75, block_below=75),
        blocking_conditions=["missing_clips", "broken_transitions", "wrong_order"],
        warning_conditions=["audio_sync_minor", "color_grade_inconsistent"],
    ),
]
