"""MVP agent contracts — the agents wired into the current graph.

Agents that are not yet invoked by a graph phase (character-dossier,
environment-bible, prompt-composition, continuity-ledger, generation-scheduler,
scene-continuity-validator, full-movie-flow-validator, kb-curator) are kept out
of the MVP roster until they are wired in. Their implementation classes and
schema tests remain in the codebase for future phases.
"""

from __future__ import annotations

from film_pipeline.schemas.base import AgentFamily, AgentRole
from film_pipeline.schemas.handoff import AgentRegistration

MVP_AGENTS: list[AgentRegistration] = [
    AgentRegistration(
        agent_id="orchestrator-agent",
        family=AgentFamily.OPERATIONS,
        role=AgentRole.ORCHESTRATOR,
        capabilities=["flow_routing", "arbitration", "phase_transition"],
        input_artifacts=["project_profile", "phase_state"],
        output_artifacts=["routing_decision"],
        allowed_kb_domains=["operations", "governance"],
        blocked_kb_domains=[],
        prompt_framework="RCTCO",
        default_model_profile="strict_validator",
        reviewed_by=["human"],
        failure_modes=["wrong_phase_transition", "stale_state"],
    ),
    AgentRegistration(
        agent_id="intake-classifier-agent",
        family=AgentFamily.PRODUCER,
        role=AgentRole.CREATOR,
        capabilities=["input_classification", "signal_extraction"],
        input_artifacts=["user_idea"],
        output_artifacts=["classified_input"],
        allowed_kb_domains=["operations"],
        blocked_kb_domains=["cost"],
        prompt_framework="RCTCO",
        default_model_profile="creative_writer",
        reviewed_by=["orchestrator-agent"],
        failure_modes=["misclassification", "missed_signal"],
    ),
    AgentRegistration(
        agent_id="film-constitution-agent",
        family=AgentFamily.DEVELOPMENT,
        role=AgentRole.CREATOR,
        capabilities=["theme_definition", "tone_setting", "visual_language"],
        input_artifacts=["classified_input", "resolved_config"],
        output_artifacts=["film_constitution"],
        allowed_kb_domains=["creative-writing", "tone"],
        blocked_kb_domains=["cost", "providers"],
        prompt_framework="RCTCO",
        default_model_profile="creative_writer",
        reviewed_by=["orchestrator-agent", "human"],
        failure_modes=["generic_tone", "weak_theme", "unfilmable_visual_language"],
    ),
    AgentRegistration(
        agent_id="treatment-agent",
        family=AgentFamily.DEVELOPMENT,
        role=AgentRole.CREATOR,
        capabilities=["treatment_writing", "act_mapping", "scene_listing"],
        input_artifacts=["film_constitution"],
        output_artifacts=["treatment", "act_map", "scene_list"],
        allowed_kb_domains=["creative-writing"],
        blocked_kb_domains=["cost", "providers"],
        prompt_framework="RCTCO",
        default_model_profile="creative_writer",
        reviewed_by=["orchestrator-agent", "human"],
        failure_modes=["missing_acts", "weak_structure", "overlong"],
    ),
    AgentRegistration(
        agent_id="screenwriter-agent",
        family=AgentFamily.SCREENWRITING,
        role=AgentRole.CREATOR,
        capabilities=["scene_writing", "dialogue", "scene_intents"],
        input_artifacts=["treatment", "act_map", "scene_list", "film_constitution"],
        output_artifacts=["script", "scene_intents"],
        allowed_kb_domains=["creative-writing", "dialogue", "character"],
        blocked_kb_domains=["cost", "providers"],
        prompt_framework="RCTCO",
        default_model_profile="creative_writer",
        reviewed_by=["orchestrator-agent", "human"],
        failure_modes=["voice_inconsistency", "tone_drift", "missing_scenes"],
    ),
    AgentRegistration(
        agent_id="structure-extractor-agent",
        family=AgentFamily.SCREENWRITING,
        role=AgentRole.CREATOR,
        capabilities=["structure_extraction", "runtime_estimation", "anchor_identification"],
        input_artifacts=["story_bible", "script"],
        output_artifacts=["execution_brief"],
        allowed_kb_domains=["operations", "creative-writing"],
        blocked_kb_domains=["cost", "providers"],
        prompt_framework="RCTCO",
        default_model_profile="schema_enforcer",
        reviewed_by=["orchestrator-agent"],
        failure_modes=["wrong_shot_count", "missed_anchor", "wrong_runtime"],
    ),
    AgentRegistration(
        agent_id="reference-strategy-planner",
        family=AgentFamily.REFERENCE,
        role=AgentRole.CREATOR,
        capabilities=["reference_planning", "quality_thresholds"],
        input_artifacts=["character_bible", "environment_bible", "film_constitution"],
        output_artifacts=["reference_strategy"],
        allowed_kb_domains=["reference-images", "visual-design"],
        blocked_kb_domains=["cost"],
        prompt_framework="RCTCO",
        default_model_profile="visual_reasoner",
        reviewed_by=["orchestrator-agent", "human"],
        failure_modes=["low_quality_refs", "missing_subjects", "moderation_risk"],
    ),
    AgentRegistration(
        agent_id="shot-design-agent",
        family=AgentFamily.DIRECTING,
        role=AgentRole.CREATOR,
        capabilities=["shot_design", "matrix_assembly", "coverage_planning"],
        input_artifacts=["script", "scene_intents", "character_bible", "environment_bible"],
        output_artifacts=["shot_bible", "master_film_matrix"],
        allowed_kb_domains=["directing", "camera"],
        blocked_kb_domains=["cost"],
        prompt_framework="RCTCO",
        default_model_profile="creative_writer",
        reviewed_by=["orchestrator-agent", "human"],
        failure_modes=["missing_coverage", "weak_shot_design", "unsupported_camera"],
    ),
    AgentRegistration(
        agent_id="provider-planning-agent",
        family=AgentFamily.PROMPT_PLANNING,
        role=AgentRole.CREATOR,
        capabilities=["provider_selection", "cost_estimation"],
        input_artifacts=["prompt_registry", "master_film_matrix", "resolved_config"],
        output_artifacts=["provider_plan"],
        allowed_kb_domains=["providers", "cost"],
        blocked_kb_domains=[],
        prompt_framework="RCTCO",
        default_model_profile="operations_triage",
        reviewed_by=["orchestrator-agent", "human"],
        failure_modes=["wrong_provider", "cost_overrun", "incompatible_capabilities"],
    ),
    AgentRegistration(
        agent_id="clip-validator",
        family=AgentFamily.QC,
        role=AgentRole.VALIDATOR,
        capabilities=["clip_quality", "prompt_adherence", "identity_consistency"],
        input_artifacts=["generated_clip", "prompt_registry", "validation_ledger"],
        output_artifacts=["validation_report"],
        allowed_kb_domains=["validation", "quality"],
        blocked_kb_domains=["cost"],
        prompt_framework="RCTCO",
        default_model_profile="strict_validator",
        reviewed_by=["orchestrator-agent", "human"],
        failure_modes=["false_pass", "missed_identity_drift", "too_lenient"],
    ),
    AgentRegistration(
        agent_id="failure-handling-agent",
        family=AgentFamily.OPERATIONS,
        role=AgentRole.OPERATOR,
        capabilities=["error_classification", "recovery_decision", "retry_policy"],
        input_artifacts=["generation_ledger", "provider_error", "budget_state"],
        output_artifacts=["failure_decision"],
        allowed_kb_domains=["operations", "providers"],
        blocked_kb_domains=[],
        prompt_framework="RCTCO",
        default_model_profile="operations_triage",
        reviewed_by=["orchestrator-agent"],
        failure_modes=["wrong_error_class", "premature_retry", "missed_escalation"],
    ),
]
