"""Typed base declaring the cross-mixin surface shared by the cockpit mixins.

The cockpit app is assembled from several mixins (``AppShell``,
``AppRenderMixin``, ``AppCommandsMixin``, ``AppActionsMixin``) combined via
multiple inheritance into a single ``FilmCockpitApp``. Each mixin calls
methods and reads attributes defined by the others. At runtime this works
fine through the final class's MRO, but ``mypy --strict`` type-checks each
mixin module in isolation and cannot see sibling-mixin members.

``AppCockpitBase`` declares the full cross-mixin surface (attributes set in
``AppShell.__init__`` plus methods implemented by exactly one mixin but
called from another) so every mixin can subclass it for typing purposes
only. It is never instantiated directly; ``AppShell`` provides the real
``__init__``/attributes, and the other mixins provide the real method
bodies. The final ``FilmCockpitApp`` composition overrides every stub here
with a concrete implementation.
"""

from __future__ import annotations

from abc import abstractmethod
from typing import Any

from textual.app import App
from textual.widgets import Button, DataTable, Input

from film_pipeline.app.services.models import ArtifactDetail, DashboardSummary, ProjectListItem
from film_pipeline.tui.gateway import StudioGateway
from film_pipeline.tui.view_models import (
    CockpitSnapshot,
    MatrixImpact,
    PhaseDetail,
    ReaderView,
    TargetSelection,
)


class AppCockpitBase(App[None]):
    """Typing-only declaration of the attributes/methods shared across mixins."""

    # Attributes assigned in AppShell.__init__.
    gateway: StudioGateway
    start_create: bool
    active_project_id: str
    snapshot: CockpitSnapshot | None
    selected_artifact: ArtifactDetail | None
    reader: ReaderView | None
    selected_target: TargetSelection | None
    matrix_filter: str
    project_filter: str
    _matrix_pivot: str
    matrix_impact: MatrixImpact | None
    pending_confirmation: str
    busy_label: str
    _table_rows: dict[str, list[dict[str, object]]]

    # AppShell methods used by other mixins.
    def _initialize_tables(self) -> None: ...

    def _set_table(
        self,
        selector: str,
        columns: list[str],
        rows: Any,
    ) -> None: ...

    def _update_context(self, text: str) -> None: ...

    # AppRenderMixin methods used by other mixins.
    @abstractmethod
    def _load_snapshot(self) -> CockpitSnapshot: ...

    def _load_dashboard(self, projects: list[ProjectListItem]) -> DashboardSummary | None: ...

    def _render_snapshot(self, snapshot: CockpitSnapshot) -> None: ...

    def _render_projects(self, projects: list[ProjectListItem]) -> None: ...

    def _render_status(
        self,
        dashboard: DashboardSummary | None,
        providers: list[dict[str, object]],
    ) -> None: ...

    def _render_matrix(self, snapshot: CockpitSnapshot) -> None: ...

    @abstractmethod
    def _scene_rows(self, snapshot: CockpitSnapshot) -> list[dict[str, object]]: ...

    @abstractmethod
    def _guide_rows(self, snapshot: CockpitSnapshot) -> list[dict[str, object]]: ...

    def _show_guide_step(self, row: dict[str, object], *, open_tab: bool = True) -> None: ...

    @abstractmethod
    def _matrix_pivot_field(self) -> str: ...

    def _update_command_palette_intelligence(self, command: str) -> None: ...

    def _show_command_help(self) -> None: ...

    def _context_for_tab(self, tab_id: str) -> None: ...

    def _render_reader(self, reader: ReaderView) -> None: ...

    def _show_generation_prompt(self, shot_id: str) -> None: ...

    @abstractmethod
    def _reader_context(self, reader: ReaderView) -> str: ...

    @abstractmethod
    def _matrix_impact_context(self, impact: MatrixImpact) -> str: ...

    @abstractmethod
    def _phase_context(self, phase_detail: PhaseDetail) -> str: ...

    # AppCommandsMixin methods used by other mixins.
    def _run_command(self, command: str) -> None: ...

    def _open_artifact(self, artifact_id: str) -> None: ...

    def _open_scene(self, scene_id: str) -> None: ...

    def _filter_matrix(self, query: str) -> None: ...

    def _pivot_matrix(self, field: str) -> None: ...

    def _switch_project(self, project_id: str) -> None: ...

    def _filter_projects(self, value: str) -> None: ...

    @abstractmethod
    def _visible_projects(self, projects: list[ProjectListItem]) -> list[ProjectListItem]: ...

    def _show_thread(self, target_id: str) -> None: ...

    def _draft_for_target(self, payload: str) -> None: ...

    def _show_phase_detail(self, phase: str, *, open_tab: bool = True) -> None: ...

    def _open_next_action(self) -> None: ...

    def _fill_command(self, command: str) -> None: ...

    def _validation_command(self, query: str) -> None: ...

    def _filter_validation(self, *, validator_id: str = "", severity: str = "") -> None: ...

    def _start_fix(self, target_id: str) -> None: ...

    def _open_target(self, target_id: str) -> None: ...

    def _reader_command(self, payload: str) -> None: ...

    def _open_reader_index(self, row: dict[str, object]) -> None: ...

    def _open_reader_link(self, target_id: str) -> None: ...

    @abstractmethod
    def _find_selection_for_target(self, target_id: str) -> TargetSelection: ...

    def _try_load_artifact_detail(self, selection: TargetSelection) -> None: ...

    def _open_review_issue_by_id(self, issue_id: str) -> None: ...

    def _open_review_issue(self, row: dict[str, object]) -> None: ...

    def _dashboard_command(self, metric: str) -> None: ...

    def _asset_command(self, payload: str) -> None: ...

    def _comment_from_command(self, payload: str) -> None: ...

    def _create_project_from_command(self, payload: str) -> None: ...

    def _artifact_row(self, artifact_id: str) -> dict[str, object] | None: ...

    # AppActionsMixin methods used by other mixins.
    def _run_in_background(
        self,
        label: str,
        work: Any,
        on_done: Any = None,
    ) -> None: ...

    def action_run_generation(self) -> None: ...

    def action_plan_generation(self) -> None: ...

    def action_approve_generation_spend(self) -> None: ...

    def action_start_generation(self) -> None: ...

    def action_poll_generation(self) -> None: ...

    def action_refresh(self) -> None: ...

    def action_open_tab(self, tab_id: str) -> None: ...

    def action_toggle_command_palette(self) -> None: ...

    def action_approve_phase(self) -> None: ...

    def action_confirm_approval(self) -> None: ...

    def action_new_project(self) -> None: ...

    def action_revise_idea(self) -> None: ...

    def action_run_validation(self) -> None: ...

    def action_request_revision(self) -> None: ...

    def action_add_comment(self) -> None: ...

    def on_button_pressed(self, event: Button.Pressed) -> None: ...

    def on_data_table_row_selected(self, event: DataTable.RowSelected) -> None: ...

    def on_input_submitted(self, event: Input.Submitted) -> None: ...

    def on_input_changed(self, event: Input.Changed) -> None: ...

    def _confirm_approval(self) -> None: ...

    def _approve_phase_now(self) -> None: ...

    def _prepare_approval_confirmation(self) -> None: ...
